### ISSUE TITLE
i want NGINX/PHP image for "RPi0 w" please

### ISSUE THREAD

**Issue by Rdivxe** [TOLDOTECHNIK/buildroot-webkit#40] opened 2021-12-06 20:34 UTC
i want NGINX/PHP image for "RPi0 w" please @TOLDOTECHNIK 
https://github.com/TOLDOTECHNIK/buildroot-webkit/issues/13#issuecomment-529283054
This does not work with Rasperby 0w. I want to run it on it because the version did not work because it is for Rasperby 3. If you please, please provide a NGINX/PHP version and I will be thankful to you. We will work on an achievement that will be cooperation and you will like it after working on it.

**Comment by TOLDOTECHNIK** [comment] 2021-12-09 10:13
Closing due to duplicate of #41

**Closed by TOLDOTECHNIK** 2021-12-09 10:13 UTC
